#!/usr/bin/env bash

alias brighter='tinty apply base16-synth-midnight-dark'
alias dark='tinty apply base16-seti'
alias darker='tinty apply base16-ayu-dark'
alias light='tinty apply base16-solarized-light'
alias lighter='tinty apply base16-one-light'
alias frappe='tinty apply base16-catppuccin-frappe'
alias latte='tinty apply base16-catppuccin-latte'
alias macchiato='tinty apply base16-catppuccin-macchiato'
alias mocha='tinty apply base16-catppuccin-mocha'

alias gpgstart='gpgconf --launch gpg-agent'
if command -v lsd >/dev/null 2>&1; then
  alias ls='lsd'
fi
alias main='git checkout main'
alias mux="tmuxinator"
alias ping='prettyping --nolegend'
alias please='sudo $(fc -ln -1)'
alias rake="noglob rake"
alias n="nvim"
alias vi='nvim'
alias weather='curl wttr.in'

alias mini='ssh teddys-mac-mini.local'
alias work='ssh teddys-shopify-macBook-pro.local'
alias omarchy='ssh omarchy-mbp'
alias nicole='ssh nicolepaik@nicoles-macbook-air.local'
