# Extra autostart processes
# exec-once = uwsm-app -- my-service

# Auto-toggle trackpad based on focused window
exec-once = ~/.local/bin/trackpad-auto-toggle

# Workspace apps
exec-once = uwsm-app -- google-chrome-stable
exec-once = uwsm-app -- xdg-terminal-exec
exec-once = uwsm-app -- google-chrome-stable --app=https://discord.com/channels/@me
exec-once = uwsm-app -- google-chrome-stable --app=https://mail.google.com
exec-once = uwsm-app -- google-chrome-stable --app=https://calendar.google.com
