vim.cmd("command! WQ wq")
vim.cmd("command! Wq wq")
vim.cmd("command! Wa wa")
vim.cmd("command! W w")
vim.cmd("command! Q q")
vim.cmd("command! Qa qa")
vim.cmd("command! Vs vs")
vim.cmd("command! VEx vex")
vim.cmd("command! Tabe tabe")

vim.cmd("command! Fzf FloatermNew fzf")
vim.cmd("command! Irb FloatermNew irb")
vim.cmd("command! Lazygit FloatermNew lazygit")
vim.cmd("command! Node FloatermNew node")
vim.cmd("command! Python FloatermNew python")
vim.cmd("command! Ranger FloatermNew ranger")
vim.cmd("command! Terminal FloatermNew")
